spring.application.name=voice-ai-api

# DB ??
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MongoDB ?? ??
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ??? CORS (??? ??)
app.cors.allow-origins=${CORS_ALLOW_ORIGINS}

# JWT ??
jwt.secret=${JWT_SECRET}
jwt.access-exp-ms=3600000

app.storage.location=uploads

spring.profiles.active=stt-ok

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

nlp.base-url=${NLP_BASE_URL}
app.backend.public-base-url=${BACKEND_PUBLIC_URL}

# OCR ?? URL
ocr.base-url=${OCR_BASE_URL}
ocr.server.url=${OCR_SERVER_URL}
ocr.server.token=${OCR_SERVER_TOKEN:}

# ???? ??(local, s3)
app.storage.type=local

# ?? ???? ?? ?? (JAR/IDE ?? ?? ??)
app.storage.local.base-dir=./capstone-storage

# ????? prefix (??�S3 ???? ??? ? ???)
app.storage.prefix.extracted=texts/extracted
app.storage.prefix.stt=texts/stt

app.storage.prefix.uploads=files/uploads

server.forward-headers-strategy=framework

# app.nlp.callback.api-key=

## S3 ?? ??
#app.storage.s3.bucket=

## AWS ??
#cloud.aws.region.static=

logging.level.com.sch.capstone.backend.filter.JwtAuthenticationFilter=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE